<!--yml
category: 未分类
date: 0001-01-01 00:00:00
--->

# 824.如果同步块内的线程抛出异常会发⽣什么？

> 原文：[https://zwmst.com/4906.html](https://zwmst.com/4906.html)

   [ *并发编程面试专栏* ](https://zwmst.com/%e5%b9%b6%e5%8f%91%e7%bc%96%e7%a8%8b%e9%9d%a2%e8%af%95%e4%b8%93%e6%a0%8f)*[ <time datetime="2021-10-13T22:59:12+08:00"> 2021-10-13 </time> ](https://zwmst.com/4906.html)  synchronized⽅法正常返回或者抛异常⽽终⽌，JVM会⾃动释放对象锁*